# Generated by Django 5.1.15 on 2026-06-11 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=200, verbose_name='Хто')),
                ('action', models.CharField(max_length=100, verbose_name='Дія')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Деталі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли')),
            ],
            options={
                'verbose_name': 'Запис журналу',
                'verbose_name_plural': 'Журнал дій',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('start_date', models.DateField(verbose_name='Початок акції')),
                ('end_date', models.DateField(verbose_name='Дедлайн подачі продажів')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кампанія',
                'verbose_name_plural': 'Кампанії',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='ПІБ')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('salon', models.CharField(max_length=200, verbose_name='Салон')),
                ('factory', models.CharField(max_length=200, verbose_name='Фабрика')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='Заблокований')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Зареєстрований')),
            ],
            options={
                'verbose_name': 'Учасник',
                'verbose_name_plural': 'Учасники',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='Дата продажу')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер замовлення')),
                ('order_number_normalized', models.CharField(editable=False, max_length=100)),
                ('salon_normalized', models.CharField(editable=False, max_length=200)),
                ('product_type', models.CharField(choices=[('sofa', 'Диван'), ('bed', 'Ліжко'), ('chair', 'Крісло'), ('other', 'Інше')], max_length=20, verbose_name='Виріб')),
                ('product_name', models.CharField(blank=True, max_length=200, verbose_name='Назва виробу (інше)')),
                ('fabric_name', models.CharField(max_length=200, verbose_name='Тканина Veloro')),
                ('doc_photo_file_id', models.CharField(max_length=300, verbose_name='Фото документа (file_id)')),
                ('doc_photo', models.FileField(blank=True, upload_to='sales/', verbose_name='Фото документа')),
                ('product_photo_file_id', models.CharField(blank=True, max_length=300, verbose_name='Фото виробу (file_id)')),
                ('product_photo', models.FileField(blank=True, upload_to='sales/', verbose_name='Фото виробу')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сума замовлення')),
                ('status', models.CharField(choices=[('pending', 'Очікує перевірки'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено')], default='pending', max_length=20, verbose_name='Статус')),
                ('reject_reason', models.TextField(blank=True, verbose_name='Причина відхилення')),
                ('duplicate_warning', models.BooleanField(default=False, verbose_name='Можливий дублікат (номер є в іншому салоні)')),
                ('moderated_by', models.CharField(blank=True, max_length=200, verbose_name='Модерував')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Час модерації')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подано')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.campaign', verbose_name='Кампанія')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='core.participant', verbose_name='Учасник')),
            ],
            options={
                'verbose_name': 'Продаж',
                'verbose_name_plural': 'Продажі',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Нараховано')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.campaign', verbose_name='Кампанія')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.participant', verbose_name='Учасник')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.sale', verbose_name='Продаж')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
            },
        ),
        migrations.CreateModel(
            name='Draw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.CharField(max_length=200, verbose_name='Приз')),
                ('tickets_total', models.PositiveIntegerField(default=0, editable=False, verbose_name='Квитків у розіграші')),
                ('performed_by', models.CharField(blank=True, editable=False, max_length=200, verbose_name='Провів')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата і час')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draws', to='core.campaign', verbose_name='Кампанія')),
                ('winner', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.participant', verbose_name='Переможець')),
                ('winning_ticket', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ticket', verbose_name='Виграшний квиток')),
            ],
            options={
                'verbose_name': 'Розіграш',
                'verbose_name_plural': 'Розіграші',
            },
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'rejected'), _negated=True), fields=('campaign', 'salon_normalized', 'order_number_normalized'), name='uniq_order_per_salon_active'),
        ),
    ]
