# Generated by Django 5.1.15 on 2026-06-12 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='uniq_order_per_salon_active',
        ),
        migrations.AlterField(
            model_name='participant',
            name='factory',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фабрика'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='doc_photo_file_id',
            field=models.CharField(blank=True, max_length=300, verbose_name='Фото документа (file_id)'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер замовлення'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='order_number_normalized',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('status', 'rejected'), _negated=True), models.Q(('order_number_normalized', ''), _negated=True)), fields=('campaign', 'salon_normalized', 'order_number_normalized'), name='uniq_order_per_salon_active'),
        ),
    ]
