# Generated by Django 5.1.15 on 2026-06-12 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sale_uniq_order_per_salon_active_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='uniq_order_per_salon_active',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='duplicate_warning',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='order_number',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='order_number_normalized',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='salon_normalized',
        ),
    ]
