# Generated by Django 5.1.15 on 2026-06-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sale_uniq_order_per_salon_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='bonus_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Фіксується в момент підтвердження продажу', max_digits=10, verbose_name='Бонус, грн'),
        ),
    ]
