# Generated by Django 5.1.15 on 2026-06-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sale_bonus_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='factory',
            field=models.CharField(blank=True, max_length=200, verbose_name='Фабрика'),
        ),
    ]
