# Generated by Django 5.1.15 on 2026-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sale_factory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Текст повідомлення')),
                ('image', models.ImageField(blank=True, upload_to='broadcasts/', verbose_name='Зображення')),
                ('recipients_total', models.PositiveIntegerField(default=0, editable=False, verbose_name='Отримувачів')),
                ('sent_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Доставлено')),
                ('sent_by', models.CharField(blank=True, editable=False, max_length=200, verbose_name='Надіслав')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Надіслано')),
            ],
            options={
                'verbose_name': 'Розсилка',
                'verbose_name_plural': 'Розсилки',
                'ordering': ['-created_at'],
            },
        ),
    ]
