# Generated by Django 5.1.15 on 2026-06-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_broadcast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcast',
            name='image',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='media',
            field=models.FileField(blank=True, upload_to='broadcasts/', verbose_name='Медіа (фото або відео)'),
        ),
    ]
